### ISSUE TITLE
Set up data source for Picker to work with Detox

### ISSUE THREAD

**Issue by j320** [react-native-community/react-native-picker#74]
# Bug

At the moment, Picker is not working with the setColumnValue() function in Detox due to data source not being set up: https://github.com/react-native-community/react-native-picker/blob/101f272af0e2de57c211f465c81a2c061c72ba4a/ios/RNCPicker.m#L25

This is blocking Detox from getting any values from the Picker and thus we can't automate testing the Picker.
 
## Environment info

```bash
    react: ^16.13.1 => 16.13.1 
    react-native: ^0.62.2 => 0.62.2 
```

This is the ticket opened in Detox with a thorough explanation on the issue: https://github.com/wix/Detox/issues/2031

**Comment by LeoNatan** [comment]
Hello,

To elaborate, the issue here is that the delegate it set up, but not the data source. The data source is necessary for the picker view to know how many components (columns) it has. There is some undocumented behavior (= can change at any moment) in UIKit that if the picker view does not have a data source set, the question of number of components is sent to the picker view itself. The solution is to set the data source to be the picker view itself, just like you set the delegate. The `UIPickerViewDataSource` protocol is already implemented in the class.

For RN's picker view implementation, we had a hack in the Detox code to workaround this, but we do not want to further extend this hack for this project. The fix is very minor.

**Comment by sammysium** [comment]
@j320 did you get this to work? I still can't get it to work; can you share your solution please? I want to select an item/option in the picker but no way so far.

**Comment by anija** [comment]
> @j320 did you get this to work? I still can't get it to work; can you share your solution please? I want to select an item/option in the picker but no way so far.

I use this code:
`if (device.getPlatform() === 'ios') {
      await element(by.id('ios_picker')).setColumnToValue(0, value);
      await element(by.id('done_text')).tap();
    } else {
      await element(by.id('android_picker').withAncestor(by.id('testID-container-view'))).tap();
      await element(by.text(value)).tap();
    }`
